baseurl = "https://kurousada.github.io/"
publishDir = "docs"
languageCode = "ja-jp"
hasCJKLanguage = true
pygmentscodefences = true
title = "Kuro Usada ga!"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
googleAnalytics = ""
canonifyurls = true
disqusShortname = "kurousada-ga"

[params]
    # Sets the meta tag description, usually reserved for the main page
    #description          = ""
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Kuro Usada ga!"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/posts/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    customCSS            = ["/css/hugo-future-imperfect.min.css", "/css/main.css"]
    customJS             = ["/js/hugo-future-imperfect.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Kuro Usada ga!"

    paragraph = "Kuro Usadaが楽しく遊ぶところです。<br>エサをあげると喜びます。"

    about     = "Ladies and gentlemen, boys and girls. Kuro Usada ga! presented by Kuro Usada began just a few minutes ago.　Every time, Kuro Usada uses his vivid imagination to create magical imagery for all to enjoy. Nothing is more wonderful than the imagination. It can be a beautiful fantasy. Or, an exciting adventure! But beware — imagination also expand your greatest fears into a nightmare. Now, get ready for kurousada.ga, — a journey beyond your wildest imagination. W-Wait! Don't get back within just few minutes... PLEASE!"

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/main/logo.png"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "Kuro Usada"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 5

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "Posts"
    url = "/posts"
    #identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "kurousada"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""
    email           = "kuro.usada+email@gmail.com"
